#nullable enable
using System;
using System.IO;
using Cipher.Game.Audio;
using UnityEditor;
using UnityEngine;

namespace Cipher.Game.Editor
{
    /// <summary>
    /// Renders the procedural sound bank to WAV files so a human can listen to it.
    ///
    ///     Unity.exe -batchmode -nographics -quit -projectPath game
    ///               -executeMethod Cipher.Game.Editor.SfxExporter.ExportAll
    ///
    /// Every sound in this game is generated by maths in Waveforms.cs, which means the only way
    /// anyone has ever judged one is by launching a build, starting a round and waiting for it to
    /// happen. That is a terrible loop for audio, where the fix is often one number and the
    /// difference is obvious in half a second of listening.
    ///
    /// Writes to art/review/, which is gitignored: these are build outputs, not assets.
    /// </summary>
    public static class SfxExporter
    {
        [MenuItem("Cipher/Audio/Export SFX to WAV")]
        public static void ExportAll()
        {
            string dir = Path.GetFullPath(Path.Combine(Application.dataPath, "../../art/review/sfx"));
            Directory.CreateDirectory(dir);

            int written = 0;
            foreach (Sfx sfx in Enum.GetValues(typeof(Sfx)))
            {
                float[] samples;
                try { samples = SoundRecipes.Build(sfx); }
                catch (Exception e) { Debug.LogWarning($"[Sfx] {sfx}: {e.Message}"); continue; }
                if (samples == null || samples.Length == 0) continue;

                string path = Path.Combine(dir, $"{sfx}.wav");
                File.WriteAllBytes(path, Wav(samples, Waveforms.SampleRate));
                written++;
                Debug.Log($"[Sfx] {sfx}: {samples.Length / (float)Waveforms.SampleRate:F3}s -> {path}");
            }
            // The loops too. They are not in the Sfx enum -- they are AudioSource clips rather
            // than one-shots -- and they are the two things a listener most wants to judge on their
            // own, because they play for the whole match.
            foreach (var (name, samples) in new[]
                     {
                         ("MusicLoop", SoundRecipes.MusicLoop()),
                         ("WindLoop", SoundRecipes.WindLoop()),
                         ("HordeLoop", SoundRecipes.HordeLoop()),
                     })
            {
                string loopPath = Path.Combine(dir, $"{name}.wav");
                File.WriteAllBytes(loopPath, Wav(samples, Waveforms.SampleRate));
                written++;
                Debug.Log($"[Sfx] {name}: {samples.Length / (float)Waveforms.SampleRate:F2}s -> {loopPath}");
            }

            Debug.Log($"[Sfx] exported {written} sounds to {dir}");
        }

        /// <summary>16-bit mono PCM. The simplest thing every player on earth can open.</summary>
        private static byte[] Wav(float[] samples, int rate)
        {
            using var mem = new MemoryStream();
            using var w = new BinaryWriter(mem);
            int dataBytes = samples.Length * 2;

            w.Write(new[] { 'R', 'I', 'F', 'F' });
            w.Write(36 + dataBytes);
            w.Write(new[] { 'W', 'A', 'V', 'E' });
            w.Write(new[] { 'f', 'm', 't', ' ' });
            w.Write(16);                       // PCM chunk size
            w.Write((short)1);                 // PCM
            w.Write((short)1);                 // mono
            w.Write(rate);
            w.Write(rate * 2);                 // byte rate
            w.Write((short)2);                 // block align
            w.Write((short)16);                // bits
            w.Write(new[] { 'd', 'a', 't', 'a' });
            w.Write(dataBytes);

            foreach (float f in samples)
                w.Write((short)(Mathf.Clamp(f, -1f, 1f) * short.MaxValue));

            w.Flush();
            return mem.ToArray();
        }
    }
}
