/* ONE OF ONE — the sound-design grammar. Every sound is built from slots
 * (what it is, how it is processed, where it sits, how a human plays it),
 * never picked whole from a short list. A one-phrase label like "dark synth
 * chord loop" points Suno at the average of thousands of tracks: the preset.
 * Specific physical detail pushes it off the average. */
"use strict";

const OneGrammar = {
  LEAD: {
    register: [
      "sitting low-mid, just above the 808",
      "in the low register under the snare",
      "dead mid register",
      "low-mid, darker than the drums",
      "one octave above the 808 root",
      "mid register, one higher note per cycle",
      "low, doubling the 808 an octave up",
      "low-mid with the top rolled off",
      "mid register, narrow range",
      "parked in the low mids around the kick's knock",
      "mid register, never above the snare's crack",
      "low-mid, stepping into the mids only on the last note",
    ],
    articulation: [
      "clipped staccato 16ths that skip the downbeat",
      "two long notes then a triplet stab",
      "off-beat stabs on the and of 2 and 4",
      "one held note per bar, cut before the snare",
      "three-against-two stabs that fight the hats",
      "dotted-8th repeats drifting across the bar line",
      "16th stutters that cut out every other bar",
      "a push note one 16th before each downbeat",
      "legato runs that slur into each other",
      "ghosted notes with one hard accent per bar",
      "stabs that only answer the snare",
      "a three-note pickup that lands on beat 1 and stops",
      "quarter-note triplets over straight drums",
      "32nd-note retriggers on the last beat of each bar",
      "long tones that start a 16th late",
      "two stabs, then two bars of silence",
      "staggered 8ths with every third note muted",
      "one anticipated stab on the last 16th of the bar",
    ],
    motif: [
      "a five-note figure that climbs a minor third and falls an octave",
      "a two-note motif bouncing a tritone",
      "a three-note cell: root, flat second, root",
      "a four-note minor descent, last note bent flat",
      "one repeated note with a single octave leap",
      "a six-note phrase circling the fifth, never resolving",
      "a nervous half-step shake turned into a riff",
      "a three-note dark minor hook with one sour note in the middle",
      "a phrase that rises a fourth, then a reply that falls a fifth",
      "a seven-note run skipping every other scale step",
      "a stubborn root note leaning on the flat sixth",
      "a four-note menacing minor figure ending on the flat second",
      "an octave-jumping two-note riff",
      "a four-note riff that starts one 16th later each bar",
      "a dark minor stab that slides down a whole step",
      "a three-note creeping climb, half step by half step, back to the root",
    ],
    // How a person plays it. The anti-quantize slot.
    human: [
      "played by hand, never snapped to the grid",
      "every note a slightly different velocity, never even twice",
      "the second note always a hair late",
      "rushed into the bar, then laid back",
      "one take with the small mistakes left in",
      "notes overlapping a little, like a player who holds too long",
      "the accent moving to a new note each pass",
      "pressure swelling and fading unevenly under the fingers",
      "timing pulled behind the snare",
      "loose and slightly ahead on the pickups",
      "a little drunk on the timing but always landing the one",
      "released early on the off-beats, so the gaps breathe",
      "bent into pitch by hand, never landing in tune twice",
      "played like someone tapping it out on a car dashboard",
    ],
    motion: [
      "it gets a little brighter each time the hook comes back",
      "it bends down a half step at the end of every phrase",
      "it jumps up an octave every 4th bar",
      "it cuts out every 8th bar, leaving the drums bare",
      "one echo of the last note hangs over into the next bar",
      "the detune widens as the loop goes on",
      "the notes get shorter every 4 bars",
      "a second copy enters an octave down at bar 9",
      "a pitch dip on the last beat of every 8 bars",
      "the last note of each phrase plays reversed",
      "it gets grittier on the second verse",
      "one note changes each pass, so it never repeats exactly",
      "it thins to half its notes, then comes back whole",
      "it drifts up a few cents over 16 bars, then snaps back",
      "hit softer, then suddenly hard on the last pass",
      "it stays frozen and identical while the drums move",
    ],
    placement: [
      "bone-dry, center, tucked right above the 808",
      "panned left with a short slapback on the right",
      "mono center, out of the kick's way",
      "wide stereo with the lows summed to mono",
      "dry up front with a small dark plate behind it",
      "tucked under the 808, never fighting it",
      "set back in a short room, drums in front",
      "a short echo on the right side only, low in the mix",
      "dry on the left, delayed on the right",
      "one copy dead center, a quiet copy far right",
      "mid-scooped so the 808 owns the low end",
      "narrow and loud, mono-compatible",
      "dry and close, delay only on the last note",
      "sitting behind the snare, louder than the hats",
    ],
  },

  BASS: {
    source: [
      "a long-decay 808",
      "a short punchy 808",
      "a distorted 808",
      "a clean sine sub",
      "a gritty distorted mono bass",
      "a mono synth bass",
      "an 808 with a hard knock on top",
      "a sub that only sustains on the root",
      "a pitched-down kick used as bass",
      "a sliding 808 with a long tail",
      "a square-wave sub",
      "a layered 808 and sine sub",
    ],
    tone: [
      "tube saturation so it shows up on phone speakers",
      "a clean round body",
      "hard-clipped grit",
      "glide between every note",
      "glide only into the downbeat",
      "a tight decay that dies before the next kick",
      "long tails that ring into the snare",
      "a click on the attack",
      "a low-pass that closes on each note",
      "a slight pitch fall at the end of every note",
      "upper harmonics brought up with distortion",
      "a short gated tail",
    ],
    pattern: [
      "following the kick exactly",
      "playing off the kick, landing in its gaps",
      "one note per bar",
      "syncopated 16ths with long rests",
      "one octave slide into the hook",
      "a slide up a fifth into each new bar",
      "silent for 2 bars, then hits",
      "three notes then nothing",
      "root and flat second only",
      "32nd stutters on the last beat",
      "holding under the lead and moving when it rests",
      "playing the lead's motif two octaves down",
      "a triplet bounce against straight hats",
      "entering a 16th late",
    ],
    human: [
      "slides played by hand, each one a different length",
      "note lengths changing every bar like a player feeling it out",
      "landing a hair behind the kick",
      "the last note of each bar played late on purpose",
      "slides that land slightly flat, then settle",
      "pushed ahead of the beat on the pickups only",
      "hit harder on the second pass, softer on the first",
      "held one beat too long now and then, like a human",
    ],
  },

  DRUMS: {
    kick: [
      "a dry knocking kick",
      "a short punchy kick with a click on top",
      "a deep thud kick with the low end cut so the 808 carries the sub",
      "a hard-clipped kick",
      "a muffled sampled kick with room on it",
      "a tight kick that hits like a car door",
      "a layered kick, sub plus knock",
      "a kick that only hits twice per bar",
      "a kick on beat 1 and the and of 3",
      "a syncopated double kick before the snare",
      "a sparse kick that skips bar 4",
      "a kick placed slightly ahead of the grid",
    ],
    snare: [
      "a crisp dry snare with a short tail",
      "a tight layered clap and snare",
      "a pitched-up snappy snare",
      "a hard sampled snare, compressed until it cracks",
      "a finger snap stacked on a clap",
      "a tight snare with a short room",
      "a clap that lands a hair late",
      "a bone-dry clap, close and hard",
      "a half-time snare on 3 only",
      "a clap with a short reverse lead-in",
      "a snare with a heavy transient snap",
      "a loose hand clap stacked three times, slightly out of sync",
    ],
    hats: [
      "tight closed hats in uneven 16ths",
      "hats rolling in threes",
      "sparse 8th hats with one open hat per bar",
      "hats that twitch into 32nds then stop dead",
      "a shaker in place of hats",
      "ticking hats panned slightly right",
      "hand-played hats, every hit a different velocity",
      "half-open hats on the off-beats",
      "hats that cut out every 4th bar",
      "trap hat rolls pitched up a step on the last beat",
      "one hat pattern that never changes",
      "crunchy bitcrushed hats",
    ],
  },

  // Twitch percussion: a sound, a rhythm, a place in time.
  TWITCH: {
    sound: [
      "a tight metallic tick",
      "a clipped hat burst",
      "a dry knock tuned to the key",
      "a bitcrushed clap fragment",
      "stuttered kick retriggers",
      "a short noise burst",
      "a pitched-up knock blip",
      "a dry wooden click",
      "a shaker ruffle",
      "a gated snare tail cut short",
      "a tiny pitched perc ping",
      "a reversed hat one-shot",
    ],
    rhythm: [
      "in 5-hit bursts that skip the grid",
      "stuttering 32nds for half a beat",
      "repeating every 3 16ths against the bar",
      "in uneven pairs, long-short",
      "in a quick double hit right before the snare",
      "in a broken 7-hit pattern that loops every 2 bars",
      "in single hits that land in random 16th slots",
      "retriggering at triple speed for one beat",
      "flamming against the hats",
      "stop-start, 3 on, 2 off",
      "rolling in threes then cutting dead",
      "in a burst that slows down as it decays",
    ],
    where: [
      "on the last beat of every 2nd bar",
      "between the kick and snare",
      "right before each downbeat",
      "only in the gaps the lead leaves",
      "answering the snare",
      "on bar 4 and bar 8 only",
      "quietly through the verse",
      "only after the switch",
      "on beat 3, never the same way twice",
      "around the 808 slides",
    ],
  },

  GROOVE: {
    sync: [
      "kicks pushed off the beat, snare dead on",
      "everything leans on the and",
      "the kick avoids beat 1 every other bar",
      "accents on the last 16th of each beat",
      "the 808 and kick anticipate the downbeat",
      "half-time snare under double-time hats",
      "the snare comes early once every 4 bars",
      "a broken kick pattern that never repeats twice",
      "kick syncopation that tracks the lead's rhythm",
      "a gap on beat 1 so the downbeat hits harder",
      "off-beat everything except the snare",
      "a full stop on beat 4 every 8 bars",
    ],
    human: [
      "unquantized, snare a hair late",
      "hats rushing slightly ahead",
      "kick drifting behind the grid",
      "16ths pushed slightly late for a trap bounce",
      "a loose pocket, played in, never snapped",
      "clap layers a few milliseconds apart",
      "quiet uneven extra snare taps",
      "percussion played live over the loop",
      "the whole loop sitting back on the beat",
      "tight kick, loose everything else",
      "a slight push into each snare",
    ],
    triplet: [
      "hats rolling in threes against straight kicks",
      "triplet hat runs every other bar",
      "quarter-note triplets in the snare pickups",
      "triplet 808 bounce on the turnaround",
      "a heavy bounce, triplets felt but not played",
      "triplet stutters only on the last beat",
      "straight hats, triplet kicks",
      "twitch percussion in threes over a straight pocket",
      "triplet bounce in the verse, straight in the hook",
    ],
  },

  SWITCH: {
    when: [
      "at the 1:30 mark",
      "halfway through",
      "after the second hook",
      "at bar 33",
      "for the last 40 seconds",
      "right after a full-stop bar",
      "when the lead cuts out",
      "after two beats of silence",
      "on the second verse",
      "for the final third",
    ],
    what: [
      "the tempo halves, same key",
      "the drums flip to a half-time pocket",
      "the lead is replaced by itself pitched down an octave",
      "the 808 goes from sparse to fast rolling 16ths",
      "the key falls a minor third",
      "the drums go dry and the lead goes huge and wet",
      "everything strips to 808 and one snare",
      "the same motif moves to a different instrument",
      "the hats go from straight to rolling in threes",
      "the kick pattern flips to the off-beats",
      "the lead stutters and slices itself up",
      "new drums, harder, distorted, louder",
      "the 808 swaps to a gritty distorted mono bass",
      "the hats double while the kick stays put",
      "only the twitch percussion and the 808 keep going",
    ],
    land: [
      "on a hard cut, straight in",
      "after one bar of silence",
      "the old lead keeps going for one bar under the new drums",
      "slowing down into it like the power got cut",
      "the 808 comes in first, drums join on bar 2",
      "a single reversed hit into the downbeat",
      "the drums cut, the lead rings alone, then everything slams back",
      "the new section starts on beat 2, not 1",
      "a pitch dive into the new key",
      "the snare stops, then restarts half-time",
    ],
  },

  TITLE: {
    a: ["Glass", "Rubber", "Copper", "Static", "Velvet", "Crooked", "Paper", "Neon", "Iron", "Loose", "Hollow", "Quiet", "Gold", "Bent", "Midnight", "Chrome"],
    b: ["Jaw", "Halo", "Receipt", "Pulse", "Lantern", "Alibi", "Engine", "Teeth", "Mirror", "Ledger", "Fuse", "Orbit", "Hinge", "Tab", "Signal", "Crown"],
  },

  MIX: "crisp modern hip hop mix, punchy, hard 808s",
};

// Instrument families. Each source is "full description|short handle"; each
// family has its own processing words, so a tuba never gets a synth's
// "ring-modulated" and a synth never gets "breath noise".
//
// Genre magnets are kept out on purpose (a test enforces it): saxophone,
// clarinet, flugelhorn, Harmon mute, rips and fall-offs (jazz); Rhodes,
// Wurlitzer, FM electric piano (elevator and smooth jazz); Hammond, Leslie,
// "wailing" harmonica, spring reverb, twang, pentatonic (blues); acid,
// squelch, supersaw, laser, chiptune, ping-pong, pumping, filter builds,
// ramps (EDM and techno). Every family is framed over trap drums and 808s.
OneGrammar.FAMILIES = {
  brass: {
    frame: "recorded hot over hard trap drums and 808s",
    sources: [
      "a full trumpet section in tight unison, regal and menacing|the trumpets",
      "a stacked French horn and trombone section, heavy and regal|the horn section",
      "a sliding tuba line that smears between notes|the tuba",
      "a bass trombone sliding down into each note|the bass trombone",
      "a brass section pitched down a whole step so it sounds enormous|the brass",
      "a sousaphone pumping the low notes|the sousaphone",
      "a lone trumpet with a cracked, raspy tone|the lone trumpet",
      "a trombone section playing short punchy swells|the trombones",
      "trumpets and tuba stacked an octave apart, villainous|the brass stack",
    ],
    character: [
      "blown so hard the brass rasps and buzzes",
      "fat and brassy, compressed into one wall of sound",
      "pitched down off an old record so it sounds heavy",
      "tight and dry, the room tail cut off",
      "doubled by a distorted 808 underneath",
      "swelling in, then cut off dead",
      "spread wide across the stereo field",
      "a little out of tune between players, so it sounds real",
      "distorted just enough to sound like it is coming out of a car trunk",
    ],
  },
  organ: {
    frame: "over hard trap drums and 808s",
    sources: [
      "a drunken detuned organ, the pitch sagging and swaying|the drunken organ",
      "a wheezing broken organ running out of air|the broken organ",
      "a cheap combo organ with a wavering vibrato|the combo organ",
      "a detuned out-of-tune piano with sticky keys, played heavy|the sticky piano",
      "a toy piano with plastic, clanky hammers|the toy piano",
      "a reversed piano chord resampled into a one-shot|the reversed piano chord",
      "a dark low piano note, struck hard and left to ring|the low piano",
    ],
    character: [
      "slurring in and out of tune like it had a few drinks",
      "keys clacking audibly under the notes",
      "pushed through a cranked tube preamp",
      "with pedal creaks and key noise left in",
      "the pitch sagging on every held chord",
      "low-passed so it sounds like it is behind a wall",
      "overdriven until the low notes snarl",
      "sample-rate reduced to a grainy edge",
    ],
  },
  wind: {
    frame: "sampled, pitched and flipped over hard trap drums and 808s",
    sources: [
      "a trap flute loop, breathy and hypnotic|the trap flute",
      "an erhu sample bending and sliding between notes|the erhu",
      "a harmonica sample pitched down and distorted|the harmonica",
      "a bamboo flute sample, overblown so it squeaks|the bamboo flute",
      "a low flute sample pitched down an octave, dark and woody|the low flute",
    ],
    character: [
      "pitched up and sped up like an old record",
      "breath and finger noise left in",
      "bent hard between notes",
      "doubled by a distorted 808 on the root",
      "run through a guitar amp until it barks",
      "time-stretched so the grain smears",
      "cut into one-bar pieces and rearranged",
      "a slight pitch warble, never steady",
    ],
  },
  guitar: {
    frame: "over hard trap drums and 808s",
    sources: [
      "a muted electric guitar through a fuzz pedal|the fuzz guitar",
      "a pitched-up soul guitar sample cut to one bar|the soul guitar sample",
      "a dark baritone guitar, picked low and close|the baritone guitar",
      "a distorted bass guitar played up high as the lead|the distorted bass guitar",
      "a pitch-bent electric guitar harmonic, sampled and looped|the guitar harmonic",
      "a detuned acoustic guitar sample, pitched down and dark|the acoustic guitar sample",
    ],
    character: [
      "palm-muted and gated tight",
      "overdriven through a small amp",
      "string squeaks and pick noise left in",
      "bent slightly flat on the long notes",
      "doubled and panned hard left and right",
      "band-passed thin like a phone speaker",
      "parallel-distorted with the clean signal on top",
    ],
  },
  synth: {
    frame: "over hard trap drums and 808s",
    sources: [
      "a rubber-band mono synth that boings on every glide|the rubber-band synth",
      "a woozy, seasick detuned synth that slides into every note|the woozy synth",
      "a syrupy slowed-down synth lead with a pitch sag|the syrupy synth",
      "a grinding, bit-mangled digital lead|the grinding lead",
      "a thick, chewy analog brass patch|the analog brass patch",
      "a squealing pitch-bent mono lead like a car alarm|the car-alarm lead",
      "a thin nagging square lead like a pager going off|the pager lead",
      "a cold detuned triangle lead, slightly out of tune|the cold triangle lead",
      "a warbling detuned synth like a phone ringing underwater|the underwater synth",
      "a distorted 808 played up an octave as the lead|the distorted 808 lead",
      "an 808 tuned and played as the melody|the 808",
    ],
    character: [
      "bitcrushed just enough to grit the attacks",
      "hard-clipped on every transient",
      "faintly ring-modulated with a metallic edge",
      "resampled down an octave so the grain shows",
      "glide time drifting slower and faster by hand",
      "gated tight so every note cuts off clean",
      "soft-clipped and glued with slow compression",
      "detuned a few cents against itself",
    ],
  },
};

// Lanes set the opening tags and which instrument families a roll can use.
OneGrammar.LANES = [
  {
    id: "southside", label: "South Side brass", weight: 2,
    anchors: ["southern trap, orchestral brass", "Atlanta trap, heavy brass", "southern hip hop, regal brass trap"],
    families: { brass: 10, organ: 1, wind: 1 },
    bass: ["a sliding tuba doubling the 808", "a sousaphone pumping the root under the 808"],
  },
  {
    id: "electronic", label: "Electronic mutant", weight: 2,
    anchors: ["experimental trap", "left-field trap", "experimental drill", "minimal experimental trap"],
    families: { synth: 6, guitar: 1 },
    bass: [],
  },
  {
    id: "crate", label: "Crate flip", weight: 2,
    anchors: ["sample-flip hip hop, hard trap drums", "experimental hip hop, flipped sample", "Detroit hip hop, flipped sample"],
    families: { wind: 4, organ: 2, guitar: 2, brass: 1 },
    bass: [],
  },
  {
    id: "syrup", label: "Drunk syrup", weight: 1,
    anchors: ["Houston slowed trap, woozy", "southern trap, slowed and syrupy"],
    families: { organ: 3, wind: 2, brass: 2 },
    bass: ["a sliding tuba doubling the 808"],
  },
  {
    id: "minimal", label: "Minimal left-field", weight: 1,
    anchors: ["minimal left-field hip hop", "experimental hip hop, minimal", "Atlanta experimental trap"],
    families: { organ: 2, guitar: 2, synth: 2, wind: 1 },
    bass: [],
  },
];

// One extra percussion color per roll, played by a person.
OneGrammar.COLOR = [
  "trap maracas shaken by hand under the hats, a little behind the beat",
  "a military snare playing tight rudiments under the hats",
  "a tambourine smacked on 2 and 4, never quite even",
  "finger snaps landing a hair late",
  "a dry woodblock knocking the off-beats",
  "a shaker played live, the accents wandering",
  "a second clap layer slapped by hand, slightly early",
];

// The counter part: a second instrument from another family, used sparingly.
OneGrammar.COUNTER_ROLE = [
  "answering the lead once every 4 bars",
  "one long held note under the hook only",
  "two notes on the turnaround, then gone",
  "doubling the last note of each lead phrase",
  "entering only after the switch",
  "a three-note reply in the gaps the lead leaves",
];

if (typeof module !== "undefined") module.exports = OneGrammar;
