/* ONE OF ONE — the sound-design grammar. Every sound is built from slots
 * (what it is, how it is processed, where it sits, how a human plays it),
 * never picked whole from a short list. A one-phrase label like "dark synth
 * chord loop" points Suno at the average of thousands of tracks: the preset.
 * Specific physical detail pushes it off the average. */
"use strict";

const OneGrammar = {
  // First words Suno reads. One specific lane, never bare "hip hop".
  ANCHORS: [
    "experimental trap",
    "minimal experimental trap",
    "left-field trap",
    "experimental hip hop, minimal",
    "Atlanta experimental trap",
    "Detroit minimal hip hop",
    "experimental drill",
    "minimal left-field hip hop",
  ],

  IDENTITY: [
    "a wound-up, nervous Atlanta record that sounds like it is sprinting and looking over its shoulder at the same time",
    "a gratitude record with clenched teeth, Detroit late night, winning but still counting what it cost",
    "a New Orleans swagger record built on almost nothing, one pitched loop, a kick and a lot of confidence in the empty space",
    "a brotherhood record from the East Atlanta side streets, loose and rowdy in the drums, deadly serious in the melody",
    "a North Carolina front-porch reflection record, unhurried, drums knocking like someone tapping a car door",
    "a morning-show freestyle record built so the host stops talking and nods for sixteen bars",
    "a Minneapolis eccentric record, smirking and off-center, every sound slightly wrong on purpose",
    "a twitchy internet-era record, clever and fast, every bar a new trick but the pocket never breaks",
    "a victory-lap record that never gets loud, letting the restraint do the flexing",
    "a paranoid two-in-the-morning record where the beat keeps changing its mind",
    "an East Atlanta elastic record, rubber-band bounce, every sound stretched and snapped back",
    "a strip-club-at-noon record, half asleep and still dangerous, built to make a room move slow",
  ],

  LEAD: {
    source: [
      "a detuned square-wave synth lead",
      "a pitched-up soul guitar sample cut to one bar",
      "a muted electric guitar through a fuzz pedal",
      "a Rhodes chord sample sliced into single stabs",
      "a Wurlitzer with a broken tremolo",
      "an 808 tuned and played as the melody",
      "a sine-wave lead with fast glide",
      "a resampled analog synth pluck",
      "a clean single-coil guitar lick, sampled and sliced",
      "a reversed piano chord resampled into a one-shot",
      "a hard-sync saw mono synth",
      "a pulse-width mono synth lead",
      "a polysynth chord stab, played mono",
      "a hollow FM electric piano",
      "a distorted bass guitar played up high as the lead",
      "a pitch-bent electric guitar harmonic, sampled and looped",
      "a squelchy filtered square bass played an octave up as the lead",
      "a woody synth pluck with a short decay",
    ],
    character: [
      "pushed through a cranked tube preamp",
      "bitcrushed just enough to grit the attacks",
      "doubled and detuned a few cents apart",
      "saturated with a slight pitch warble",
      "low-passed hard so only the body speaks",
      "band-passed thin like a phone speaker",
      "hard-clipped on every transient",
      "chorus-widened with a slow drift in the pitch",
      "resampled down an octave so the grain shows",
      "sample-rate reduced to a grainy edge",
      "parallel-distorted with the clean signal on top",
      "overdriven through a small guitar amp",
      "gated tight so every note cuts off clean",
      "faintly ring-modulated with a metallic edge",
      "heavily compressed so the tails come up loud",
      "soft-clipped and glued with slow compression",
    ],
    register: [
      "sitting low-mid, just above the 808",
      "in the low register under the snare",
      "dead mid register",
      "low-mid, darker than the drums",
      "one octave above the 808 root",
      "mid register, one higher note per cycle",
      "low, doubling the 808 an octave up",
      "low-mid with the top rolled off",
      "mid register, narrow range",
      "parked in the low mids around the kick's knock",
      "mid register, never above the snare's crack",
      "low-mid, stepping into the mids only on the last note",
    ],
    articulation: [
      "clipped staccato 16ths that skip the downbeat",
      "two long notes then a triplet stab",
      "off-beat stabs on the and of 2 and 4",
      "one held note per bar, cut before the snare",
      "three-against-two stabs that fight the hats",
      "dotted-8th repeats drifting across the bar line",
      "16th stutters that cut out every other bar",
      "a push note one 16th before each downbeat",
      "legato runs that slur into each other",
      "ghosted notes with one hard accent per bar",
      "stabs that only answer the snare",
      "a three-note pickup that lands on beat 1 and stops",
      "quarter-note triplets over straight drums",
      "32nd-note retriggers on the last beat of each bar",
      "long tones that start a 16th late",
      "two stabs, then two bars of silence",
      "staggered 8ths with every third note muted",
      "one anticipated stab on the last 16th of the bar",
    ],
    motif: [
      "a five-note figure that climbs a minor third and falls an octave",
      "a two-note motif bouncing a tritone",
      "a three-note cell: root, flat second, root",
      "a four-note minor descent, last note bent flat",
      "one repeated note with a single octave leap",
      "a six-note phrase circling the fifth, never resolving",
      "a half-step trill turned into a riff",
      "a three-note minor pentatonic hook with a flat-five passing tone",
      "a call that rises a fourth and an answer that falls a fifth",
      "a seven-note run skipping every other scale step",
      "a stubborn root note leaning on the flat sixth",
      "a four-note Phrygian figure ending on the flat second",
      "an octave-jumping two-note riff",
      "a four-note riff that starts one 16th later each bar",
      "a minor-ninth stab that slides down a whole step",
      "a three-note chromatic climb resolving to the root",
    ],
    // How a person plays it. The anti-quantize slot.
    human: [
      "played by hand, never snapped to the grid",
      "every note a slightly different velocity, never even twice",
      "the second note always a hair late",
      "rushed into the bar, then laid back",
      "one take with the small mistakes left in",
      "notes overlapping a little, like a player who holds too long",
      "the accent moving to a new note each pass",
      "pressure swelling and fading unevenly under the fingers",
      "timing pulled behind the snare",
      "loose and slightly ahead on the pickups",
      "a little drunk on the timing but always landing the one",
      "released early on the off-beats, so the gaps breathe",
      "bent into pitch by hand, never landing in tune twice",
      "played like someone tapping it out on a car dashboard",
    ],
    motion: [
      "the low-pass opens slowly across 8 bars",
      "it bends down a half step at the end of every phrase",
      "it jumps up an octave every 4th bar",
      "it cuts out every 8th bar, leaving the drums bare",
      "the delay feedback climbs until the switch",
      "the detune widens as the loop goes on",
      "the notes get shorter every 4 bars",
      "a second copy enters an octave down at bar 9",
      "a pitch dip on the last beat of every 8 bars",
      "the last note of each phrase plays reversed",
      "the bitcrush gets heavier toward the hook",
      "one note changes each pass, so it never repeats exactly",
      "it thins to half its notes, then comes back whole",
      "it drifts up a few cents over 16 bars, then snaps back",
      "velocity swells, then snaps back hard",
      "it stays frozen and identical while the drums move",
    ],
    placement: [
      "bone-dry, center, tucked right above the 808",
      "panned left with a short slapback on the right",
      "mono center, ducked by every kick",
      "wide stereo with the lows summed to mono",
      "dry up front with a small dark plate behind it",
      "ducking hard under every 808 hit so it breathes",
      "set back in a short room, drums in front",
      "an eighth-note ping-pong delay, low in the mix",
      "dry on the left, delayed on the right",
      "one copy dead center, a quiet copy far right",
      "mid-scooped so the 808 owns the low end",
      "narrow and loud, mono-compatible",
      "dry and close, delay only on the last note",
      "sitting behind the snare, louder than the hats",
    ],
  },

  BASS: {
    source: [
      "a long-decay 808",
      "a short punchy 808",
      "a distorted 808",
      "a clean sine sub",
      "two detuned saw basses beating against each other",
      "a mono synth bass",
      "an 808 with a hard knock on top",
      "a sub that only sustains on the root",
      "a pitched-down kick used as bass",
      "a muted fingered electric bass",
      "a square-wave sub",
      "a layered 808 and sine sub",
    ],
    tone: [
      "tube saturation so it shows up on phone speakers",
      "a clean round body",
      "hard-clipped grit",
      "glide between every note",
      "glide only into the downbeat",
      "a tight decay that dies before the next kick",
      "long tails that ring into the snare",
      "a click on the attack",
      "a low-pass that closes on each note",
      "a slight pitch fall at the end of every note",
      "upper harmonics brought up with distortion",
      "a short gated tail",
    ],
    pattern: [
      "following the kick exactly",
      "playing off the kick, landing in its gaps",
      "one note per bar",
      "syncopated 16ths with long rests",
      "octave jumps on the pickup",
      "a slide up a fifth into each new bar",
      "silent for 2 bars, then hits",
      "three notes then nothing",
      "root and flat second only",
      "32nd stutters on the last beat",
      "holding under the lead and moving when it rests",
      "playing the lead's motif two octaves down",
      "a triplet bounce against straight hats",
      "entering a 16th late",
    ],
    human: [
      "slides played by hand, each one a different length",
      "note lengths changing every bar like a player feeling it out",
      "landing a hair behind the kick",
      "the last note of each bar played late on purpose",
      "slides that land slightly flat, then settle",
      "pushed ahead of the beat on the pickups only",
      "hit harder on the second pass, softer on the first",
      "held one beat too long now and then, like a human",
    ],
  },

  DRUMS: {
    kick: [
      "a dry knocking kick",
      "a short punchy kick with a click on top",
      "a deep thud kick with the low end cut so the 808 carries the sub",
      "a hard-clipped kick",
      "a muffled sampled kick with room on it",
      "a tight kick that ducks everything",
      "a layered kick, sub plus knock",
      "a kick that only hits twice per bar",
      "a kick on beat 1 and the and of 3",
      "a syncopated double kick before the snare",
      "a sparse kick that skips bar 4",
      "a kick placed slightly ahead of the grid",
    ],
    snare: [
      "a crisp dry snare with a short tail",
      "a tight layered clap and snare",
      "a pitched-up snappy snare",
      "a sampled break snare, compressed hard",
      "a finger snap stacked on a clap",
      "a gated room snare",
      "a clap that lands a hair late",
      "a side-stick click",
      "a half-time snare on 3 only",
      "a clap with a short reverse lead-in",
      "a snare with a heavy transient snap",
      "a loose hand clap stacked three times, slightly out of sync",
    ],
    hats: [
      "tight closed hats in uneven 16ths",
      "hats rolling in threes",
      "sparse 8th hats with one open hat per bar",
      "hats that twitch into 32nds then stop dead",
      "a shaker in place of hats",
      "ticking hats panned slightly right",
      "hand-played hats, every hit a different velocity",
      "half-open hats on the off-beats",
      "hats that cut out every 4th bar",
      "pitched hat rolls ramping up",
      "one hat pattern that never changes",
      "crunchy bitcrushed hats",
    ],
  },

  // Twitch percussion: a sound, a rhythm, a place in time.
  TWITCH: {
    sound: [
      "a tight metallic tick",
      "a clipped hat burst",
      "a dry knock tuned to the key",
      "a bitcrushed clap fragment",
      "stuttered kick retriggers",
      "a short noise burst",
      "a pitched-up knock blip",
      "a granular click",
      "a shaker ruffle",
      "a gated snare tail cut short",
      "a tiny pitched perc ping",
      "a reversed hat one-shot",
    ],
    rhythm: [
      "in 5-hit bursts that skip the grid",
      "stuttering 32nds for half a beat",
      "repeating every 3 16ths against the bar",
      "in uneven pairs, long-short",
      "ramping faster into the snare",
      "in a broken 7-hit pattern that loops every 2 bars",
      "in single hits that land in random 16th slots",
      "retriggering at triple speed for one beat",
      "flamming against the hats",
      "stop-start, 3 on, 2 off",
      "rolling in threes then cutting dead",
      "in a burst that slows down as it decays",
    ],
    where: [
      "on the last beat of every 2nd bar",
      "between the kick and snare",
      "right before each downbeat",
      "only in the gaps the lead leaves",
      "answering the snare",
      "on bar 4 and bar 8 only",
      "quietly through the verse",
      "only after the switch",
      "on beat 3, never the same way twice",
      "around the 808 slides",
    ],
  },

  GROOVE: {
    sync: [
      "kicks pushed off the beat, snare dead on",
      "everything leans on the and",
      "the kick avoids beat 1 every other bar",
      "accents on the last 16th of each beat",
      "the 808 and kick anticipate the downbeat",
      "half-time snare under double-time hats",
      "the snare comes early once every 4 bars",
      "a broken kick pattern that never repeats twice",
      "kick syncopation that tracks the lead's rhythm",
      "a gap on beat 1 so the downbeat hits harder",
      "off-beat everything except the snare",
      "a full stop on beat 4 every 8 bars",
    ],
    human: [
      "unquantized, snare a hair late",
      "hats rushing slightly ahead",
      "kick drifting behind the grid",
      "16ths swung about 57 percent",
      "a loose pocket, played in, never snapped",
      "clap layers a few milliseconds apart",
      "quiet uneven ghost notes on the snare",
      "percussion played live over the loop",
      "the whole loop sitting back on the beat",
      "tight kick, loose everything else",
      "a slight push into each snare",
    ],
    triplet: [
      "hats rolling in threes against straight kicks",
      "triplet hat runs every other bar",
      "quarter-note triplets in the snare pickups",
      "triplet 808 bounce on the turnaround",
      "a heavy bounce, triplets felt but not played",
      "triplet stutters only on the last beat",
      "straight hats, triplet kicks",
      "twitch percussion in threes over a straight pocket",
      "triplet bounce in the verse, straight in the hook",
    ],
  },

  SWITCH: {
    when: [
      "at the 1:30 mark",
      "halfway through",
      "after the second hook",
      "at bar 33",
      "for the last 40 seconds",
      "right after a full-stop bar",
      "when the lead cuts out",
      "after two beats of silence",
      "on the second verse",
      "for the final third",
    ],
    what: [
      "the tempo halves, same key",
      "the drums flip to a half-time pocket",
      "the lead is replaced by itself pitched down an octave",
      "the 808 goes from sparse to fast rolling 16ths",
      "the key falls a minor third",
      "the drums go dry and the lead goes huge and wet",
      "everything strips to 808 and one snare",
      "the same motif moves to a different instrument",
      "the hats go from straight to rolling in threes",
      "the kick pattern flips to the off-beats",
      "the lead stutters and slices itself up",
      "new drums, harder, distorted, louder",
      "the bass swaps from 808 to two detuned saw basses",
      "the tempo jumps up and the hats double",
      "only the twitch percussion and the 808 keep going",
    ],
    land: [
      "on a hard cut, straight in",
      "after one bar of silence",
      "the old lead keeps going for one bar under the new drums",
      "slowing down into it like the power got cut",
      "the 808 comes in first, drums join on bar 2",
      "a single reversed hit into the downbeat",
      "the drums cut, the lead rings alone, then everything slams back",
      "the new section starts on beat 2, not 1",
      "a pitch dive into the new key",
      "the snare stops, then restarts half-time",
    ],
  },

  TITLE: {
    a: ["Glass", "Rubber", "Copper", "Static", "Velvet", "Crooked", "Paper", "Neon", "Iron", "Loose", "Hollow", "Quiet", "Gold", "Bent", "Midnight", "Chrome"],
    b: ["Jaw", "Halo", "Receipt", "Pulse", "Lantern", "Alibi", "Engine", "Teeth", "Mirror", "Ledger", "Fuse", "Orbit", "Hinge", "Tab", "Signal", "Crown"],
  },

  MIX: "crisp modern mix, punchy and loud, clean low end",
};

if (typeof module !== "undefined") module.exports = OneGrammar;
