/* ONE OF ONE — the sound-design grammar. Every sound is built from slots
 * (what it is, how it is processed, where it sits, how a human plays it),
 * never picked whole from a short list. A one-phrase label like "dark synth
 * chord loop" points Suno at the average of thousands of tracks: the preset.
 * Specific physical detail pushes it off the average. */
"use strict";

const OneGrammar = {
  LEAD: {
    register: [
      "sitting low-mid, just above the 808",
      "in the low register under the snare",
      "dead mid register",
      "low-mid, darker than the drums",
      "one octave above the 808 root",
      "mid register, one higher note per cycle",
      "low, doubling the 808 an octave up",
      "low-mid with the top rolled off",
      "mid register, narrow range",
      "parked in the low mids around the kick's knock",
      "mid register, never above the snare's crack",
      "low-mid, stepping into the mids only on the last note",
    ],
    articulation: [
      "clipped staccato 16ths that skip the downbeat",
      "two long notes then a triplet stab",
      "off-beat stabs on the and of 2 and 4",
      "one held note per bar, cut before the snare",
      "three-against-two stabs that fight the hats",
      "dotted-8th repeats drifting across the bar line",
      "16th stutters that cut out every other bar",
      "a push note one 16th before each downbeat",
      "legato runs that slur into each other",
      "ghosted notes with one hard accent per bar",
      "stabs that only answer the snare",
      "a three-note pickup that lands on beat 1 and stops",
      "quarter-note triplets over straight drums",
      "32nd-note retriggers on the last beat of each bar",
      "long tones that start a 16th late",
      "two stabs, then two bars of silence",
      "staggered 8ths with every third note muted",
      "one anticipated stab on the last 16th of the bar",
    ],
    motif: [
      "a five-note figure that climbs a minor third and falls an octave",
      "a two-note motif bouncing a tritone",
      "a three-note cell: root, flat second, root",
      "a four-note minor descent, last note bent flat",
      "one repeated note with a single octave leap",
      "a six-note phrase circling the fifth, never resolving",
      "a half-step trill turned into a riff",
      "a three-note minor pentatonic hook with a flat-five passing tone",
      "a call that rises a fourth and an answer that falls a fifth",
      "a seven-note run skipping every other scale step",
      "a stubborn root note leaning on the flat sixth",
      "a four-note Phrygian figure ending on the flat second",
      "an octave-jumping two-note riff",
      "a four-note riff that starts one 16th later each bar",
      "a minor-ninth stab that slides down a whole step",
      "a three-note chromatic climb resolving to the root",
    ],
    // How a person plays it. The anti-quantize slot.
    human: [
      "played by hand, never snapped to the grid",
      "every note a slightly different velocity, never even twice",
      "the second note always a hair late",
      "rushed into the bar, then laid back",
      "one take with the small mistakes left in",
      "notes overlapping a little, like a player who holds too long",
      "the accent moving to a new note each pass",
      "pressure swelling and fading unevenly under the fingers",
      "timing pulled behind the snare",
      "loose and slightly ahead on the pickups",
      "a little drunk on the timing but always landing the one",
      "released early on the off-beats, so the gaps breathe",
      "bent into pitch by hand, never landing in tune twice",
      "played like someone tapping it out on a car dashboard",
    ],
    motion: [
      "the low-pass opens slowly across 8 bars",
      "it bends down a half step at the end of every phrase",
      "it jumps up an octave every 4th bar",
      "it cuts out every 8th bar, leaving the drums bare",
      "the delay feedback climbs until the switch",
      "the detune widens as the loop goes on",
      "the notes get shorter every 4 bars",
      "a second copy enters an octave down at bar 9",
      "a pitch dip on the last beat of every 8 bars",
      "the last note of each phrase plays reversed",
      "the bitcrush gets heavier toward the hook",
      "one note changes each pass, so it never repeats exactly",
      "it thins to half its notes, then comes back whole",
      "it drifts up a few cents over 16 bars, then snaps back",
      "velocity swells, then snaps back hard",
      "it stays frozen and identical while the drums move",
    ],
    placement: [
      "bone-dry, center, tucked right above the 808",
      "panned left with a short slapback on the right",
      "mono center, ducked by every kick",
      "wide stereo with the lows summed to mono",
      "dry up front with a small dark plate behind it",
      "ducking hard under every 808 hit so it breathes",
      "set back in a short room, drums in front",
      "an eighth-note ping-pong delay, low in the mix",
      "dry on the left, delayed on the right",
      "one copy dead center, a quiet copy far right",
      "mid-scooped so the 808 owns the low end",
      "narrow and loud, mono-compatible",
      "dry and close, delay only on the last note",
      "sitting behind the snare, louder than the hats",
    ],
  },

  BASS: {
    source: [
      "a long-decay 808",
      "a short punchy 808",
      "a distorted 808",
      "a clean sine sub",
      "two detuned saw basses beating against each other",
      "a mono synth bass",
      "an 808 with a hard knock on top",
      "a sub that only sustains on the root",
      "a pitched-down kick used as bass",
      "a muted fingered electric bass",
      "a square-wave sub",
      "a layered 808 and sine sub",
    ],
    tone: [
      "tube saturation so it shows up on phone speakers",
      "a clean round body",
      "hard-clipped grit",
      "glide between every note",
      "glide only into the downbeat",
      "a tight decay that dies before the next kick",
      "long tails that ring into the snare",
      "a click on the attack",
      "a low-pass that closes on each note",
      "a slight pitch fall at the end of every note",
      "upper harmonics brought up with distortion",
      "a short gated tail",
    ],
    pattern: [
      "following the kick exactly",
      "playing off the kick, landing in its gaps",
      "one note per bar",
      "syncopated 16ths with long rests",
      "octave jumps on the pickup",
      "a slide up a fifth into each new bar",
      "silent for 2 bars, then hits",
      "three notes then nothing",
      "root and flat second only",
      "32nd stutters on the last beat",
      "holding under the lead and moving when it rests",
      "playing the lead's motif two octaves down",
      "a triplet bounce against straight hats",
      "entering a 16th late",
    ],
    human: [
      "slides played by hand, each one a different length",
      "note lengths changing every bar like a player feeling it out",
      "landing a hair behind the kick",
      "the last note of each bar played late on purpose",
      "slides that land slightly flat, then settle",
      "pushed ahead of the beat on the pickups only",
      "hit harder on the second pass, softer on the first",
      "held one beat too long now and then, like a human",
    ],
  },

  DRUMS: {
    kick: [
      "a dry knocking kick",
      "a short punchy kick with a click on top",
      "a deep thud kick with the low end cut so the 808 carries the sub",
      "a hard-clipped kick",
      "a muffled sampled kick with room on it",
      "a tight kick that ducks everything",
      "a layered kick, sub plus knock",
      "a kick that only hits twice per bar",
      "a kick on beat 1 and the and of 3",
      "a syncopated double kick before the snare",
      "a sparse kick that skips bar 4",
      "a kick placed slightly ahead of the grid",
    ],
    snare: [
      "a crisp dry snare with a short tail",
      "a tight layered clap and snare",
      "a pitched-up snappy snare",
      "a sampled break snare, compressed hard",
      "a finger snap stacked on a clap",
      "a gated room snare",
      "a clap that lands a hair late",
      "a side-stick click",
      "a half-time snare on 3 only",
      "a clap with a short reverse lead-in",
      "a snare with a heavy transient snap",
      "a loose hand clap stacked three times, slightly out of sync",
    ],
    hats: [
      "tight closed hats in uneven 16ths",
      "hats rolling in threes",
      "sparse 8th hats with one open hat per bar",
      "hats that twitch into 32nds then stop dead",
      "a shaker in place of hats",
      "ticking hats panned slightly right",
      "hand-played hats, every hit a different velocity",
      "half-open hats on the off-beats",
      "hats that cut out every 4th bar",
      "pitched hat rolls ramping up",
      "one hat pattern that never changes",
      "crunchy bitcrushed hats",
    ],
  },

  // Twitch percussion: a sound, a rhythm, a place in time.
  TWITCH: {
    sound: [
      "a tight metallic tick",
      "a clipped hat burst",
      "a dry knock tuned to the key",
      "a bitcrushed clap fragment",
      "stuttered kick retriggers",
      "a short noise burst",
      "a pitched-up knock blip",
      "a granular click",
      "a shaker ruffle",
      "a gated snare tail cut short",
      "a tiny pitched perc ping",
      "a reversed hat one-shot",
    ],
    rhythm: [
      "in 5-hit bursts that skip the grid",
      "stuttering 32nds for half a beat",
      "repeating every 3 16ths against the bar",
      "in uneven pairs, long-short",
      "ramping faster into the snare",
      "in a broken 7-hit pattern that loops every 2 bars",
      "in single hits that land in random 16th slots",
      "retriggering at triple speed for one beat",
      "flamming against the hats",
      "stop-start, 3 on, 2 off",
      "rolling in threes then cutting dead",
      "in a burst that slows down as it decays",
    ],
    where: [
      "on the last beat of every 2nd bar",
      "between the kick and snare",
      "right before each downbeat",
      "only in the gaps the lead leaves",
      "answering the snare",
      "on bar 4 and bar 8 only",
      "quietly through the verse",
      "only after the switch",
      "on beat 3, never the same way twice",
      "around the 808 slides",
    ],
  },

  GROOVE: {
    sync: [
      "kicks pushed off the beat, snare dead on",
      "everything leans on the and",
      "the kick avoids beat 1 every other bar",
      "accents on the last 16th of each beat",
      "the 808 and kick anticipate the downbeat",
      "half-time snare under double-time hats",
      "the snare comes early once every 4 bars",
      "a broken kick pattern that never repeats twice",
      "kick syncopation that tracks the lead's rhythm",
      "a gap on beat 1 so the downbeat hits harder",
      "off-beat everything except the snare",
      "a full stop on beat 4 every 8 bars",
    ],
    human: [
      "unquantized, snare a hair late",
      "hats rushing slightly ahead",
      "kick drifting behind the grid",
      "16ths swung about 57 percent",
      "a loose pocket, played in, never snapped",
      "clap layers a few milliseconds apart",
      "quiet uneven ghost notes on the snare",
      "percussion played live over the loop",
      "the whole loop sitting back on the beat",
      "tight kick, loose everything else",
      "a slight push into each snare",
    ],
    triplet: [
      "hats rolling in threes against straight kicks",
      "triplet hat runs every other bar",
      "quarter-note triplets in the snare pickups",
      "triplet 808 bounce on the turnaround",
      "a heavy bounce, triplets felt but not played",
      "triplet stutters only on the last beat",
      "straight hats, triplet kicks",
      "twitch percussion in threes over a straight pocket",
      "triplet bounce in the verse, straight in the hook",
    ],
  },

  SWITCH: {
    when: [
      "at the 1:30 mark",
      "halfway through",
      "after the second hook",
      "at bar 33",
      "for the last 40 seconds",
      "right after a full-stop bar",
      "when the lead cuts out",
      "after two beats of silence",
      "on the second verse",
      "for the final third",
    ],
    what: [
      "the tempo halves, same key",
      "the drums flip to a half-time pocket",
      "the lead is replaced by itself pitched down an octave",
      "the 808 goes from sparse to fast rolling 16ths",
      "the key falls a minor third",
      "the drums go dry and the lead goes huge and wet",
      "everything strips to 808 and one snare",
      "the same motif moves to a different instrument",
      "the hats go from straight to rolling in threes",
      "the kick pattern flips to the off-beats",
      "the lead stutters and slices itself up",
      "new drums, harder, distorted, louder",
      "the bass swaps from 808 to two detuned saw basses",
      "the tempo jumps up and the hats double",
      "only the twitch percussion and the 808 keep going",
    ],
    land: [
      "on a hard cut, straight in",
      "after one bar of silence",
      "the old lead keeps going for one bar under the new drums",
      "slowing down into it like the power got cut",
      "the 808 comes in first, drums join on bar 2",
      "a single reversed hit into the downbeat",
      "the drums cut, the lead rings alone, then everything slams back",
      "the new section starts on beat 2, not 1",
      "a pitch dive into the new key",
      "the snare stops, then restarts half-time",
    ],
  },

  TITLE: {
    a: ["Glass", "Rubber", "Copper", "Static", "Velvet", "Crooked", "Paper", "Neon", "Iron", "Loose", "Hollow", "Quiet", "Gold", "Bent", "Midnight", "Chrome"],
    b: ["Jaw", "Halo", "Receipt", "Pulse", "Lantern", "Alibi", "Engine", "Teeth", "Mirror", "Ledger", "Fuse", "Orbit", "Hinge", "Tab", "Signal", "Crown"],
  },

  MIX: "crisp modern mix, punchy and loud, clean low end",
};

// Instrument families. Each source is "full description|short handle"; each
// family has its own processing words, so a tuba never gets a synth's
// "ring-modulated" and a synth never gets "breath noise".
OneGrammar.FAMILIES = {
  brass: {
    frame: "recorded hot over hard trap drums",
    sources: [
      "a full trumpet section in tight unison|the trumpets",
      "a muted trumpet with a Harmon mute, buzzing and nasal|the muted trumpet",
      "a stacked French horn and trombone section, heavy and regal|the horn section",
      "a sliding tuba line that smears between notes|the tuba",
      "a bass trombone with long greasy smears|the bass trombone",
      "a baritone sax honking low and gritty|the baritone sax",
      "a flugelhorn doubled by a trumpet an octave up|the flugelhorn",
      "a big brass section pitched down a whole step so it sounds enormous|the brass",
      "a sousaphone pumping the low notes|the sousaphone",
      "a lone trumpet with a cracked, breathy tone|the lone trumpet",
      "a trombone section playing short punchy swells|the trombones",
    ],
    character: [
      "blown so hard the brass rasps and buzzes",
      "fat and brassy, compressed into one wall of sound",
      "pitched down off an old record so it sounds heavy",
      "with a rip up into every phrase",
      "with fall-offs at the end of each phrase",
      "tight and dry, the room tail cut off",
      "doubled by a distorted 808 underneath",
      "flutter-tongued and snarling on the long notes",
      "swelling in, then cut off dead",
      "spread wide across the stereo field like a section on the field",
      "a little out of tune between players, so it sounds real",
    ],
  },
  organ: {
    frame: "over hard hip hop drums",
    sources: [
      "a drunken Hammond organ with the Leslie spinning out of time|the drunken organ",
      "a wheezing pump organ running out of air|the pump organ",
      "a cheap combo organ with a wavering vibrato|the combo organ",
      "a detuned saloon piano with sticky keys|the saloon piano",
      "a Wurlitzer with a broken tremolo|the Wurlitzer",
      "a Rhodes with one cracked tine that rattles|the Rhodes",
      "a toy piano with plastic, clanky hammers|the toy piano",
      "a hollow FM electric piano|the FM electric piano",
      "a reversed piano chord resampled into a one-shot|the reversed piano chord",
    ],
    character: [
      "slurring in and out of tune like it had a few drinks",
      "the Leslie speaker speeding up and slowing down unevenly",
      "keys clacking audibly under the notes",
      "pushed through a cranked tube preamp",
      "with pedal creaks and key noise left in",
      "the pitch sagging on every held chord",
      "low-passed so it sounds like it is behind a wall",
      "chorus-thickened and slightly seasick",
      "overdriven until the low notes snarl",
      "sample-rate reduced to a grainy edge",
    ],
  },
  wind: {
    frame: "sampled and flipped over hard trap drums like a crate find",
    sources: [
      "an erhu sample bending and sliding between notes|the erhu",
      "a harmonica wailing in short bent bursts|the harmonica",
      "a breathy wooden flute with the air noise left in|the flute",
      "a bamboo flute, overblown so it squeaks|the bamboo flute",
      "a melodica with a reedy honk|the melodica",
      "an alto sax playing short smeared phrases|the alto sax",
      "a tenor sax snarling in the low register|the tenor sax",
      "a clarinet sample pitched down an octave, dark and woody|the clarinet",
    ],
    character: [
      "pitched up and sped up like an old record",
      "breath and finger noise left in",
      "bent hard between notes",
      "doubled by a distorted 808 on the root",
      "run through a guitar amp until it barks",
      "time-stretched so the grain smears",
      "cut into one-bar pieces and rearranged",
      "low-passed and saturated so it sits like a sample",
      "a slight pitch warble, never steady",
    ],
  },
  guitar: {
    frame: "over hard trap drums",
    sources: [
      "a muted electric guitar through a fuzz pedal|the fuzz guitar",
      "a pitched-up soul guitar sample cut to one bar|the soul guitar sample",
      "a baritone guitar with heavy tremolo|the baritone guitar",
      "a distorted bass guitar played up high as the lead|the distorted bass guitar",
      "a clean single-coil guitar lick, sampled and sliced|the guitar lick",
      "a pitch-bent electric guitar harmonic, sampled and looped|the guitar harmonic",
      "a 12-string electric guitar picked hard and close|the 12-string guitar",
    ],
    character: [
      "palm-muted and gated tight",
      "a spring reverb shaking on every hit",
      "overdriven through a small amp",
      "string squeaks and pick noise left in",
      "bent slightly flat on the long notes",
      "doubled and panned hard left and right",
      "band-passed thin like a phone speaker",
      "parallel-distorted with the clean signal on top",
    ],
  },
  synth: {
    frame: "over hard trap drums",
    sources: [
      "a rubber-band mono synth that boings on every glide|the rubber-band synth",
      "a gurgling, squelchy resonant mono synth like water down a drain|the squelchy synth",
      "a buzzing hornet-swarm saw lead|the hornet saw lead",
      "a glassy, brittle digital lead that sounds about to shatter|the glassy lead",
      "a woozy, seasick detuned synth that slides into every note|the woozy synth",
      "a cartoon laser-zap synth with fast pitch dives|the laser synth",
      "a busted game-console square lead with a cheap edge|the game-console lead",
      "a syrupy slowed-down synth lead with a pitch sag|the syrupy synth",
      "a grinding, bit-mangled digital lead|the grinding lead",
      "a thick, chewy analog brass patch|the analog brass patch",
      "a squealing pitch-bent mono lead like a car alarm|the car-alarm lead",
      "a hollow sine lead that glides like a theremin|the theremin-like sine",
      "a fizzy overdriven saw thinned down to a single oscillator|the fizzy saw",
      "an 808 tuned and played as the melody|the 808",
    ],
    character: [
      "bitcrushed just enough to grit the attacks",
      "hard-clipped on every transient",
      "faintly ring-modulated with a metallic edge",
      "resampled down an octave so the grain shows",
      "the filter snapping open on every accent",
      "glide time drifting slower and faster by hand",
      "gated tight so every note cuts off clean",
      "soft-clipped and glued with slow compression",
      "detuned a few cents against itself",
      "the pitch envelope zapping down on every note",
    ],
  },
};

// Lanes set the opening tags and which instrument families a roll can use.
OneGrammar.LANES = [
  {
    id: "southside", label: "South Side brass", weight: 2,
    anchors: ["southern trap, orchestral brass", "Atlanta trap, big brass section", "southern hip hop, regal brass trap"],
    families: { brass: 10, organ: 1, wind: 1 },
    bass: ["a sliding tuba doubling the 808", "a sousaphone pumping the root under the 808"],
  },
  {
    id: "electronic", label: "Electronic mutant", weight: 2,
    anchors: ["experimental trap", "left-field trap", "experimental drill", "minimal experimental trap"],
    families: { synth: 6, guitar: 1 },
    bass: [],
  },
  {
    id: "crate", label: "Crate flip", weight: 2,
    anchors: ["sample-flip hip hop, hard trap drums", "experimental hip hop, flipped sample", "Detroit hip hop, flipped sample"],
    families: { wind: 4, organ: 2, guitar: 2, brass: 1 },
    bass: [],
  },
  {
    id: "swamp", label: "Drunk swamp", weight: 1,
    anchors: ["southern hip hop, slow and swampy", "Houston slowed trap, woozy"],
    families: { organ: 3, wind: 2, brass: 2 },
    bass: ["a sliding tuba doubling the 808"],
  },
  {
    id: "minimal", label: "Minimal left-field", weight: 1,
    anchors: ["minimal left-field hip hop", "experimental hip hop, minimal", "Atlanta experimental trap"],
    families: { organ: 2, guitar: 2, synth: 2, wind: 1 },
    bass: [],
  },
];

// One extra percussion color per roll, played by a person.
OneGrammar.COLOR = [
  "maracas shaken by hand, a little behind the beat",
  "a military snare playing tight rudiments under the hats",
  "a marching bass drum thumping the downbeats",
  "a tambourine smacked on 2 and 4, never quite even",
  "finger snaps landing a hair late",
  "a woodblock knocking the off-beats",
  "a metal pipe struck once per bar, ringing in the key",
  "a shaker played live, the accents wandering",
  "a struck glass bottle tuned to the key",
  "a guiro scrape on the and of 4",
  "a frame drum slapped with the fingers, off the grid",
];

// The counter part: a second instrument from another family, used sparingly.
OneGrammar.COUNTER_ROLE = [
  "answering the lead once every 4 bars",
  "one long held note under the hook only",
  "two notes on the turnaround, then gone",
  "doubling the last note of each lead phrase",
  "entering only after the switch",
  "a three-note reply in the gaps the lead leaves",
];

if (typeof module !== "undefined") module.exports = OneGrammar;
