/* ANOMALY producer blueprints. Each one is a record identity, not a genre
 * bucket: the opener is the first thing Suno reads and it is different for
 * every blueprint. `spirit` names the reference for the UI only; a lint keeps
 * every name out of the prompt. Vocabulary rule: modern hip hop and R&B
 * production words only. No film-score, world, folk or lo-fi sound-design
 * words, no voices, no FX words, no mallets. */
"use strict";

const AnomalyBlueprints = [
  // ---------------------------------------------------------------- hip hop
  {
    id: "broward-raw", label: "Broward raw", spirit: "XXXTentacion", aliases: ["xxxtentacion", "xxx", "jahseh"],
    family: "hiphop", genre: "distorted raw trap instrumental", bpm: [128, 160], feel: "raw half-time knock", tonalities: ["minor"],
    openers: [
      "raw distorted trap: a lonely clean electric-guitar loop over a blown-out 808 that clips the whole mix on every hit, drums that slap, and sudden holes of silence",
      "aggressive emotional trap built on a two-note guitar loop and an 808 so hot it distorts the snare, drop-outs to nothing then back in at full force",
      "stripped-down distorted trap: one sad guitar figure, one blown-out 808, hard dry drums, and the beat stopping dead for a bar before slamming back",
    ],
    drums: ["hard dry snare that slaps, kick buried under the 808, hats barely there", "sparse drums with a clipped snare on 3 and long gaps", "hard raw drums, snare late and loud"],
    lowEnd: ["blown-out distorted 808 that clips the mix on every hit", "808 that swallows the kick and rings into the next bar"],
    leads: ["lonely clean electric-guitar loop, two notes", "sad palm-muted electric-guitar figure", "distorted low guitar loop"],
    clash: ["a distorted 808 slide that becomes the melody", "a reversed guitar swell", "a hard clipped snare hit", "a sudden full-band stop"],
    moves: ["the whole beat cuts to silence for a full bar every 8 bars, then slams back", "the 808 distorts harder every hook", "the guitar loop drops an octave for the last 4 bars"],
  },
  {
    id: "texas-trunk", label: "Texas trunk menace", spirit: "BigXthaPlug", aliases: ["bigxthaplug", "big x the plug", "big x"],
    family: "hiphop", genre: "hard Texas trap instrumental", bpm: [138, 150], feel: "slow heavy trunk knock", tonalities: ["minor"],
    openers: [
      "slow heavy Texas trap built for a trunk: huge 808 slides that take a whole beat to land, one cold minor synth riff, and a snare that cracks like a gunshot",
      "menacing Dallas trap with the drums pulled back and the 808 pushed forward, a sparse dark synth riff, everything slowed down and unhurried",
      "big-bodied southern trap: enormous sliding 808, hard clap-snare, hats that rattle then vanish, a dark string-stab riff as the only melody",
    ],
    drums: ["hard cracking clap-snare on 3, kick sparse, hats that rattle in bursts then vanish", "slow half-time drums with a gunshot snare and bare hats", "sparse drums where the 808 does the work, snare on 3 only"],
    lowEnd: ["huge 808 slides that take a whole beat to land", "tuned 808 so long each note runs into the next, sliding down a fifth at phrase ends"],
    leads: ["cold dark synth riff, two notes", "dark synth-brass riff, slow and unhurried", "dark string-stab riff"],
    clash: ["a low brass stab on the 1 of every 8 bars", "a pitched-down synth stab", "a distorted 808 slide", "a hard clap roll into the hook"],
    moves: ["everything but the 808 drops for the last 2 bars of every 8", "the 808 slides up an octave on the final beat of every hook", "the snare disappears for one bar every 16 while the 808 keeps knocking"],
  },
  {
    id: "king-horns", label: "King of the South horns", spirit: "T.I.", aliases: ["t.i.", "tip", "king of the south"],
    family: "hiphop", genre: "Atlanta trap instrumental with horn hits", bpm: [120, 150], feel: "proud bouncing half-time", tonalities: ["minor"],
    openers: [
      "minimal Atlanta trap with punchy horn hits on the downbeats, crisp snare rolls, a short string stab, and an 808 knock, nothing else filling the space",
      "a proud Atlanta trap beat built on staccato brass stabs, crisp snare rolls, a short string hit, and an 808 that hits once per bar",
      "horn-led minimal trap: a three-note brass stab riff, a crisp rolling snare, wide silence between every hit, and a heavy 808 knock",
    ],
    drums: ["crisp snare rolls in tight 16ths, kick on 1 and the and-of-3, crisp hat rolls", "crisp trap hats with a rolling snare and a big clap on 3", "snare roll into the downbeat of every 4 bars"],
    lowEnd: ["808 knock on the 1 and the and-of-3, short and proud", "808 that hits once per bar and lets the horns breathe"],
    leads: ["punchy staccato horn-stab riff, three notes", "low brass-stab riff, short and proud", "string-stab riff with a brass answer"],
    clash: ["a low brass swell under the last bar of every hook", "a short string stab answering the horns", "a crisp snare roll on the and-of-4", "a synth-brass hit doubling the horns"],
    moves: ["the horns drop out for the verse and return on the hook an octave down", "the snare roll doubles speed for the last 4 bars", "the horns play one beat late for the beat switch"],
  },
  {
    id: "cash-money-bounce", label: "Cash Money bounce", spirit: "Lil Wayne / Mannie Fresh", aliases: ["lil wayne", "weezy", "wayne", "mannie fresh", "cash money", "hot boys"],
    family: "hiphop", genre: "New Orleans bounce instrumental", bpm: [92, 108], feel: "bouncing call-and-answer skip", tonalities: ["minor"],
    openers: [
      "a New Orleans bounce beat: punchy synth stabs answering each other, a syncopated triggerman kick pattern, skittering hats, a big clap on 2 and 4, an 808 that talks back to the kick",
      "early-2000s southern bounce with stabby synth-brass hits in a question-and-answer pattern, drums that skip across the bar, and a bass that jumps octaves",
      "bouncy New Orleans beat built on a two-chord synth stab riff, rapid clap and hat interplay, and a kick that never lands where you expect",
    ],
    drums: ["triggerman kick pattern skipping across the bar, big clap on 2 and 4, skittering hats", "bouncy syncopated kicks with a clap that doubles on the and-of-4", "rapid hat and clap interplay with a kick that skips before beat 3"],
    lowEnd: ["808 that answers the kick pattern and jumps an octave every 4 bars", "short bouncy 808 tuned to the stabs, hitting between the kicks"],
    leads: ["punchy synth-brass stab riff in question-and-answer", "stabby two-chord synth riff, dry and short", "square-wave stab riff with a bouncing rhythm"],
    clash: ["a low synth-brass blurt on the 1", "a pitched synth stab answer on the and-of-4", "a hard clap roll", "a sub drop on the downbeat of every 8 bars"],
    moves: ["the stabs and drums trade bars: one bar stabs only, one bar drums only", "the clap doubles into a rapid roll on the last beat of every 4 bars", "the 808 walks up the scale for one bar every 8"],
  },
  {
    id: "toronto-nocturnal", label: "Toronto nocturnal", spirit: "Drake / 40", aliases: ["drake", "drizzy", "ovo", "noah 40", "40 shebib"],
    family: "hiphop", genre: "nocturnal minimal trap instrumental", bpm: [66, 96], feel: "submerged half-time drift", tonalities: ["minor"],
    openers: [
      "a nocturnal Toronto beat heard through a wall: the whole track low-pass filtered for the verse, then opening up wide on the hook, deep sub swells under airy pads",
      "underwater minimal trap: distant muffled drums, a sub that moves in slow whole notes, a hazy pad riff, and a filter that opens for 8 bars then closes again",
      "late-night minimal beat with the drums pulled way back, a warm detuned pad riff, deep sub swells, and one filtered electric-keys phrase drifting behind the beat",
    ],
    drums: ["distant muffled drums with a soft snap on 3 and hats far in the back", "sparse half-time drums low-passed until the hook", "slow kick and snap with hats that barely register"],
    lowEnd: ["deep sub swells moving in slow whole notes", "sub that dips a whole step under the fourth chord and holds"],
    leads: ["hazy detuned pad riff drifting behind the beat", "filtered electric-keys phrase, two chords", "warm pad riff with a slow filter opening"],
    clash: ["a reversed pad swell", "a muted guitar note answering the pad", "an echoing clap on the and-of-2", "a filtered synth stab"],
    moves: ["the low-pass filter opens on every hook and slams shut on the verse", "the drums drop to nothing for the last 4 bars of every 16", "the sub slides up an octave for one beat at every phrase end"],
  },
  {
    id: "east-atlanta-elastic", label: "East Atlanta elastic", spirit: "JID", aliases: ["jid", "j.i.d", "dreamville"],
    family: "hiphop", genre: "bouncy technical southern hip hop instrumental", bpm: [88, 150], feel: "rubbery double-time twitch", tonalities: ["minor"],
    openers: [
      "a rubbery, twitchy Atlanta beat made for fast technical flows: warm elastic bassline bouncing off dry punchy drums, off-kilter hats, and a dusty sampled-keys riff that gets flipped every 8 bars",
      "dry, punchy, hyperactive hip hop beat: rubber-band bass, snappy snare, hats that skip and double, a beat switch that halves the tempo without warning, and a sampled string loop as the hook",
      "an elastic technical beat with drums that feel hand-hit, bass that bends between notes, a dusty sample riff, and stop-start gaps where the whole thing drops out for a beat",
    ],
    drums: ["dry punchy snappy drums, hats that skip and double, kick stumbling early", "hand-hit-feeling drums with a cracking snare and off-kilter hats", "tight dry kit with hats in a 3-3-2 pattern and a snare that lands early"],
    lowEnd: ["warm rubbery elastic bassline bending between notes", "rubber-band synth bass bouncing off the kick, sliding into every root"],
    leads: ["dusty sampled-keys riff flipped every 8 bars", "sampled string loop", "warm electric-keys riff with a bounce"],
    clash: ["a muted synth-brass stab", "a distorted guitar stab on the and-of-4", "a pitched-down sample hit", "a rubbery bass slide"],
    moves: ["the tempo halves for 4 bars then snaps back at full speed", "the whole beat drops out for exactly one beat every 4 bars", "the sample riff plays backwards for one bar every 16"],
  },
  {
    id: "houston-psych", label: "Houston psychedelic", spirit: "Travis Scott", aliases: ["travis scott", "la flame", "cactus jack"],
    family: "hiphop", genre: "psychedelic trap instrumental", bpm: [130, 155], feel: "huge half-time haze", tonalities: ["minor"],
    openers: [
      "a psychedelic trap beat: everything soaked in a huge reverb, a detuned synth wail as the only melody, booming 808 glides, and a beat switch at the midpoint into something darker and slower",
      "hazy huge half-time trap with long reverb tails, a warped synth riff, 808s that glide between notes, and a mid-song switch to a stripped darker beat",
      "psychedelic haze trap: reversed pad swells, a detuned synth riff, booming 808 slides, and a hard beat switch that drops the tempo and the key",
    ],
    drums: ["half-time drums with a booming snare and hats in rolling triplets", "sparse hats with sudden triplet bursts, snare soaked in reverb", "kicks placed off the grid, clap a 16th late"],
    lowEnd: ["booming 808 glides between notes, tuned and saturated", "huge sub 808 that swells and takes over the room"],
    leads: ["detuned synth wail riff", "warped synth riff with pitch bends", "reversed pad riff, two notes"],
    clash: ["a reversed cymbal into every hook", "a distorted guitar stab soaked in reverb", "a low brass stab once every 8 bars", "a pitched-down synth hit"],
    moves: ["the beat switches to a darker slower beat in a new key at the midpoint", "the reverb cuts to bone-dry for one bar every 8", "the 808 glides a full octave for one beat at the end of each hook"],
  },
  {
    id: "chicago-icy", label: "Chicago icy drill", spirit: "Chief Keef / Young Chop", aliases: ["chief keef", "young chop", "sosa"],
    family: "hiphop", genre: "icy Chicago drill instrumental", bpm: [138, 148], feel: "cold rattling half-time", tonalities: ["minor"],
    openers: [
      "an icy Chicago drill beat: a cold bell riff in a minor key, hard-hitting 808 on the downbeats, hi-hat rolls that rattle like chains, and a snare on 3 like a door slamming",
      "cold hard drill with a detuned bell riff, rolling hats, an 808 that punches instead of slides, and a silence before every hook",
      "minimal icy drill built on a three-note bell riff, hard 808 hits, and hats that roll then cut dead",
    ],
    drums: ["hard snare on 3 like a slammed door, kick on 1 and the and-of-2, rattling hat rolls", "rolling 16th hats that cut dead before the snare", "hard clap-snare with hats in triplet bursts"],
    lowEnd: ["hard punching 808 on the downbeats, stabbed not slid", "808 that hits with the kick and rings exactly one beat"],
    leads: ["cold detuned bell riff, three notes", "icy synth riff in a minor key", "dark pitched-down bell riff"],
    clash: ["a short string stab under the bells", "a hard synth hit on the 1 of every 8 bars", "a distorted guitar stab", "a reversed bell swell"],
    moves: ["a full beat of silence before every hook downbeat", "the bells drop an octave for the second half of every hook", "the hats cut dead for the last bar of every 8"],
  },
  {
    id: "compton-hard", label: "Compton hard", spirit: "Kendrick / Sounwave", aliases: ["kendrick", "lamar", "sounwave", "k dot"],
    family: "hiphop", genre: "West Coast hard hip hop instrumental", bpm: [88, 140], feel: "hard-snare bounce", tonalities: ["minor"],
    openers: [
      "a West Coast beat that changes character every 8 bars: a hard cracking snare, deep sub, a tense two-note synth riff, then a sudden tempo switch into a slower darker section",
      "dramatic Compton hip hop: sparse hard drums, one tense minor string-stab riff, a bass that drops out for whole bars, and a mid-song switch that flips the drums and the key",
      "minimal West Coast hip hop with a snare that cracks, a pitched-down sample riff, and the beat rebuilding itself twice",
    ],
    drums: ["hard cracking snare on 2 and 4, kick sparse, hats loose", "dry hard drums with a snare that lands early and a kick that lands late", "sparse drums with a cracking snare and hats in 3-3-2"],
    lowEnd: ["deep sub that drops out for whole bars then returns on the 1", "808 tuned low, hitting on the and-of-3 only"],
    leads: ["tense two-note synth riff", "pitched-down sample riff", "tense string-stab riff"],
    clash: ["a reversed snare on beat 4 every 8th bar", "a low brass stab that lands a 16th early", "a distorted guitar hit", "a pitched-down synth stab"],
    moves: ["the beat switches tempo and key at the midpoint", "the drums rebuild from nothing over 8 bars", "the riff plays a tritone off the key for one bar every 16"],
  },
  {
    id: "memphis-crunk", label: "Memphis crunk", spirit: "Three 6 Mafia (instrumental)", aliases: ["three 6 mafia", "three six mafia", "juicy j", "dj paul"],
    family: "hiphop", genre: "dark Memphis crunk instrumental", bpm: [136, 150], feel: "dark bouncing crunk stomp", tonalities: ["minor"],
    openers: [
      "a dark Memphis crunk beat: a menacing low synth riff, an 808 and heavy clap on every other beat, a low brass stab, and a bounce that makes the whole room stomp",
      "grimy Memphis crunk built on a menacing synth riff, thick claps, an 808 knock, and a brass hit on the 1 of every 4 bars",
      "dark bouncy crunk: a low menacing synth, big claps, hard 808, and a high synth answer that gets under your skin",
    ],
    drums: ["heavy claps on 2 and 4 with a kick that bounces across the bar", "thick clap-snare with rolling hats and a stomping kick", "crunk drums with a clap that doubles on the and-of-4"],
    lowEnd: ["808 knock on every kick, short and heavy", "808 that drops an octave on beat 3 of every fourth bar"],
    leads: ["menacing low synth riff, two chords", "dark bouncing synth riff", "dark synth-brass riff"],
    clash: ["a low brass hit on the 1 of every 4 bars", "a high synth answer on the and-of-4", "a hard clap roll", "a distorted 808 slide"],
    moves: ["the claps drop out for one bar every 8 while the 808 keeps stomping", "the synth riff drops an octave on every hook", "the brass hit moves to the and-of-1 for the beat switch"],
  },
  {
    id: "baton-rouge-pain", label: "Baton Rouge pain", spirit: "Kevin Gates / Boosie", aliases: ["kevin gates", "boosie"],
    family: "hiphop", genre: "Louisiana pain-trap instrumental", bpm: [72, 145], feel: "rolling Louisiana bounce", tonalities: ["minor"],
    openers: [
      "a Louisiana pain beat: a dark minor string riff, rolling bounce drums, a rumbling 808, and a low bell tone that rings once per bar",
      "rolling Baton Rouge bounce with a dark minor riff, aggressive hat rolls, a rumbling 808, and gaps where only the riff plays",
      "brooding southern bounce built on a dark minor riff, rolling drums and a deep 808 that never stops moving",
    ],
    drums: ["rolling bounce drums with aggressive hat rolls and a hard clap on 3", "rolling kicks with a clap that lands late and hats in bursts", "bouncing drums with a snare roll into every 4th bar"],
    lowEnd: ["dark rumbling 808 that never stops moving, sliding between roots", "deep pulsing 808 in 8ths under the riff"],
    leads: ["dark minor string riff", "dark synth riff in minor", "pitched-down electric-keys riff"],
    clash: ["a low bell tone once per bar", "a distorted guitar stab on the and-of-2", "a low brass swell", "a pitched-down synth hit"],
    moves: ["the drums drop and only the riff plays for 2 bars every 8", "the 808 slides up a fifth on the and-of-3 every 4 bars", "the riff doubles an octave up for every hook"],
  },
  {
    id: "detroit-flint", label: "Detroit / Flint", spirit: "Babyface Ray / Rio da Yung OG", aliases: ["babyface ray", "rio da yung og"],
    family: "hiphop", genre: "Detroit bounce instrumental", bpm: [90, 105], feel: "stumbling off-grid straight time", tonalities: ["minor"],
    openers: [
      "a Detroit beat where the bass is the melody: a pitched 808 running up and down a minor scale in 8ths, drums that stumble off the grid, a nervous synth riff, and zero polish",
      "off-grid Flint bounce: unquantized drums that lurch, a walking 808 bassline as the hook, tense two-note synth stabs, everything tight and loud",
      "stumbling Detroit beat: the 808 plays the tune, the kick lands wherever it wants, the snare cracks dry, and a nervous synth loops one bar forever",
    ],
    drums: ["straight-time kick on 1 and the and-of-3, dry cracking snare on 2 and 4", "loose 8th hats lurching behind the grid with a stumbling kick", "drums alone for 2 bars before the bass, deliberately unquantized"],
    lowEnd: ["melodic pitched 808 bassline running up and down the minor scale, the bass is the hook", "bouncing 808 melody jumping an octave every fourth bar"],
    leads: ["nervous synth riff, one bar", "tense two-note synth stab", "dark electric-keys riff under the bass"],
    clash: ["a low synth-brass blurt on the 1", "a short string stab", "a distorted guitar hit on the and-of-4", "a hard clap roll"],
    moves: ["the drums stop for one bar every 8 while the bass keeps walking", "the 808 walks up an octave on every fourth bar", "the riff drops out for the verse and the bass carries it alone"],
  },
  {
    id: "ny-sample-drill", label: "NY sample drill", spirit: "Cash Cobain / 808Melo", aliases: ["cash cobain", "808melo", "pop smoke"],
    family: "hiphop", genre: "New York drill instrumental", bpm: [138, 146], feel: "sliding menacing skip", tonalities: ["minor"],
    openers: [
      "a New York drill beat with a flipped sample as the hook, sliding 808s that glide between root and fifth, drill hats that skip in triplets, and a snare on 3 that drags late",
      "dark sample drill: a warm sampled-keys riff, a sliding 808 pattern, skipping hats, and a clap under the snare that lands behind",
      "sexy-drill flip: a chorused electric-keys riff over a drill kick grid, a sliding 808, and a triple kick every 2 bars",
    ],
    drums: ["drill kick on the and-of-1 and 3-and, snare on 3 dragging late, rolling hats", "triplet hat skips alternating every bar with a late clap under the snare", "drill grid softened with a clap on 3 and a triple kick every 2 bars"],
    lowEnd: ["sliding 808 gliding root, minor third, fifth in 8ths", "808 swelling into every slide, dropping out on beat 4 of every fourth bar"],
    leads: ["warm sampled-keys riff, flipped", "chorused electric-keys riff", "dark string-stab riff"],
    clash: ["a muted electric-guitar riff with slapback", "a low bell tone", "a reversed cymbal into the hook", "a low brass stab"],
    moves: ["the sample riff plays backwards for the last bar of every 8", "the 808 slides a full octave on the final beat of every hook", "the hats cut dead for a bar every 16"],
  },
  {
    id: "west-coast", label: "West Coast bounce", spirit: "Mustard / Hit-Boy", aliases: ["mustard", "dj mustard", "hit-boy", "hit boy"],
    family: "hiphop", genre: "West Coast bounce instrumental", bpm: [96, 104], feel: "slapping cocky bounce", tonalities: ["minor"],
    openers: [
      "a West Coast slapper: punchy kick on 1 and the and-of-2, a huge clap on 2 and 4, a thick synth bass doubling the 808, and a sine-wave synth riff with pitch bends that everybody remembers",
      "ratchet bounce: dry loud drums, a two-note bass figure, sharp synth-brass stabs on the offbeats, and one riff that loops until it is impossible to forget",
      "cocky West Coast minimalism: big clap, slapping 808, a square-wave riff, and a beat that leaves whole beats empty",
    ],
    drums: ["punchy kick on 1 and the and-of-2, big clap on 2 and 4, loose 8th hats", "dry snare with a late doubled clap and an open hat on the and-of-3", "kick that hits an extra 16th before beat 3 for the bounce"],
    lowEnd: ["thick synth bass doubling a slapping 808 on a 2-bar syncopated figure", "808 that drops out on beat 3 of every fourth bar and slams back on 4"],
    leads: ["sine-wave synth riff with pitch bends", "square-wave riff, two notes", "sharp synth-brass stab riff"],
    clash: ["a short string stab on the 1 of every bar", "a synth-brass hit", "a hard clap roll", "a distorted 808 slide"],
    moves: ["beat 4 is left completely empty every bar", "the clap doubles into a roll on the last beat of every 8", "the riff drops out for the verse and returns doubled on the hook"],
  },
  {
    id: "dark-trap-blockbuster", label: "Blockbuster dark trap", spirit: "Metro Boomin / Southside", aliases: ["metro boomin", "metro", "southside", "808 mafia"],
    family: "hiphop", genre: "dark trap instrumental", bpm: [130, 150], feel: "huge half-time", tonalities: ["minor"],
    openers: [
      "a huge dark trap beat: a low string-stab riff on a minor pedal, a distorted 808 that hits like a door, hats in machine-gun rolls, and a single bell riff over the top",
      "dark blockbuster trap: big string stabs, an 808 with a clipped attack and a long tail, a low brass hit on the 1 of every 8 bars, and drums that leave silence before every hook",
      "dark minimal trap with one string-stab riff, a distorted 808, and a brass stab that only appears once every 16 bars",
    ],
    drums: ["hard snare on 3, kick on 1 and the and-of-2, hats in machine-gun rolls every 2 bars", "half-time drums with a hard clap-snare and hat rolls that accelerate", "sparse kicks with a snare that lands a 16th late and hats in 64th bursts"],
    lowEnd: ["distorted 808 with a clipped attack and a long mono tail", "808 that slides a fifth at the end of every 4 bars"],
    leads: ["dark string-stab riff on a minor pedal", "bell riff over held strings", "dark synth-brass riff"],
    clash: ["a low brass hit on the 1 of every 8 bars", "a hard clap roll into the hook", "a reversed string swell", "a distorted 808 slide"],
    moves: ["a full beat of silence before every hook", "the strings drop out and the 808 carries the melody for 4 bars", "the hats cut to nothing for the beat switch"],
  },
  // ---------------------------------------------------------------- R&B
  {
    id: "dark-synth-rnb", label: "Dark synth R&B", spirit: "The Weeknd / Illangelo", aliases: ["weeknd", "the weeknd", "illangelo", "xo"],
    family: "rnb", genre: "dark synth R&B instrumental", bpm: [62, 100], feel: "night-drive pulse", tonalities: ["minor"],
    openers: [
      "a dark R&B beat for a night drive: cold detuned synth pads, a deep booming sub, drums that snap far away, and a low synth riff that repeats like headlights on a wet road",
      "nocturnal synth R&B: big reverb, a slow pulse, a warm analog pad riff, and an 808 that only moves when the chords do",
      "dark glossy R&B with a detuned synth riff, deep sub swells, dry tight snaps, and a mid-song switch into a faster half-time pulse",
    ],
    drums: ["slow drums with a distant snap on 3 and hats in swung 16ths", "soft thudding kick, layered snap-clap on 3, hats that drop for the last 2 bars of 8", "dry tight snaps with a kick only on 1 and the and-of-2"],
    lowEnd: ["deep booming sub, one note per chord, felt not heard", "808 that dips a whole step on the fourth chord"],
    leads: ["cold detuned synth riff", "warm analog pad riff in minor ninths", "pulsing synth riff, two notes"],
    clash: ["a tremolo guitar note answering the pad", "a reversed pad swell into every hook", "a single bell tone", "a filtered synth stab"],
    moves: ["the mix drops to mono for the first beat of every hook", "the sub slides an octave down on the final beat of every phrase", "the pad cuts hard to silence for the last 8th of every 4 bars"],
  },
  {
    id: "trap-soul", label: "Trap-soul", spirit: "Bryson Tiller", aliases: ["bryson tiller", "tiller", "pen griffey"],
    family: "rnb", genre: "trap soul instrumental", bpm: [60, 72], feel: "smooth weighty half-time", tonalities: ["minor", "major"],
    openers: [
      "a trap-soul beat: a lush chorused electric-keys riff in minor ninths, a warm long 808 gliding under the chords, a snappy snare on 3, double-time hats with lazy rolls",
      "late-night trap-soul built on a slow clean guitar riff, a deep 808 that pushes an 8th early, and hats that swing late and drop out for beat 4",
      "smooth weighty R&B trap with a silky string riff, a warm 808 on the chord roots, and reverb tails cut short before every snare",
    ],
    drums: ["soft kick on 1 and the and-of-3, snappy snare on 3, double-time hats with lazy rolls", "hats swinging late and dropping for beat 4 every second bar", "layered clap-snare with a dark plate, rushed hats"],
    lowEnd: ["warm long 808 on the chord roots, gliding down an octave at phrase ends", "808 hitting an 8th before the downbeat, pushing the loop forward"],
    leads: ["lush chorused electric-keys riff in minor ninths", "slow clean electric-guitar riff", "silky string riff"],
    clash: ["a pitched-down bell, two notes, only in the hook", "a muted guitar harmonic", "a low brass swell", "a filtered synth stab"],
    moves: ["the 808 dips a whole step on the fourth chord", "the drums drop for the last 2 bars of every 8", "the keys riff drops an octave on the beat switch"],
  },
  {
    id: "afro-rnb", label: "Afro R&B", spirit: "Tems / Rema", aliases: ["tems", "rema", "burna"],
    family: "rnb", genre: "Afro R&B instrumental", bpm: [95, 110], feel: "rolling swung warmth", tonalities: ["minor", "major"],
    openers: [
      "an Afro R&B groove: log-drum bass hitting on the syncopated kick accents, a shaker in swung 16ths, a clean electric-guitar riff, and a kick that pushes the and-of-4 into the next bar",
      "warm rolling Afro-fusion R&B with a bouncing 808 sliding root to sixth, wood-tick percussion on the offbeats, and a chorused electric-keys comping riff",
      "swinging Afro R&B built on a clean guitar riff, a log-drum bass, and drums that roll instead of hit",
    ],
    drums: ["soft kick on 1 and the and-of-2, snappy snare on 3, shaker in swung 16ths", "wood-tick percussion on the offbeats with rolling swung hats", "kick pushing the and-of-4 into the next bar"],
    lowEnd: ["log-drum bass hits on the kick accents, pitched to the chords", "warm 808 sliding root to sixth in a bouncing 2-bar phrase"],
    leads: ["clean electric-guitar riff", "warm chorused electric-keys comping riff", "soft synth-pluck riff with slides"],
    clash: ["a log-drum accent on the and-of-4", "a low brass swell", "a muted guitar stab", "a soft synth-bell answer"],
    moves: ["the log drum drops out for one bar every 8", "the guitar riff plays a beat late for the beat switch", "the shaker doubles speed for the last 4 bars"],
  },
  {
    id: "y2k-rnb", label: "Y2K R&B", spirit: "Timbaland / Darkchild era", aliases: ["timbaland", "darkchild", "rodney jerkins"],
    family: "rnb", genre: "Y2K R&B instrumental", bpm: [88, 100], feel: "swung glossy bounce", tonalities: ["minor", "major"],
    openers: [
      "an early-2000s R&B beat: a snappy layered snare on 2 and 4, swung 16th hats, a kick that skips the 3, glossy chorused electric-keys chords with suspended fourths, and a punchy synth bass on a syncopated figure",
      "Y2K R&B built on a clicking drum machine pattern, a filtered clean-guitar riff, a synth stab every 4 bars, and a bass that skips",
      "glossy 2000s R&B with a staccato drum pattern, a shimmering string riff with an octave lift in the hook, and a punchy sub following the bass",
    ],
    drums: ["snappy layered snare on 2 and 4, swung 16th hats, kick skipping the 3", "crisp drum-machine hats with a shaker, ghost snares on the and-of-4", "tight dry kick doubling on the and-of-1 every second bar"],
    lowEnd: ["punchy short synth bass on a syncopated 2-bar figure", "warm sub 808 following the bass an octave down"],
    leads: ["glossy chorused electric-keys riff with suspended fourths", "filtered clean electric-guitar riff", "shimmering string riff"],
    clash: ["a synth stab every 4 bars", "a staccato string hit", "a cheap 80s synth-brass hit", "a filtered guitar stab"],
    moves: ["the keys widen in the hook and narrow in the verse", "the bass figure skips its first note every second bar", "the strings lift an octave on the last hook"],
  },
];

if (typeof module !== "undefined") module.exports = AnomalyBlueprints;
